---
title: "Workshop 4 Group B"
---

```{r setupB4, include=FALSE}

#define variables for each group: city and hospital name, infectious agent and disease, group letter
city_name <- "Baltyre"
hosp_name <- "Queen's College"
dis_name <- "influenza"
inf_agent <- "Alphainfluenzavirus influenzae"
inf_type <- "vir"
group <- "B"
groupseed <- 1234
```
{{< include ../workshop3/_includes/setup.qmd >}}
{{< include _includes/setup4.qmd >}}

::: panel-tabset
## Minutes from the last Emergency Pandemic Response Team Meeting {.unnumbered}

At the previous emergency pandemic response team meeting, the following action points were agreed:

* Testing and halting the sale of contaminated bird products

* Increase awareness of the importance of personal hygiene, hand washing, hand sanitisers etc and have resources (e.g. posters and leaflets) available in public spaces for educating public 

* Providing rapid and at home influenza antigen-dependent immunological diagnostic assay testing

* vaccination program against H9N2 for all potentially affected bird species 

* Making antiviral medications (oseltamivir and zanamivir) more accessible to all positive patients by supplying them in pharmacies and allowing prescription after evidence of a positive at-home diagnostic test

## Data collected for the current Emergency Pandemic Response Team Meeting {.unnumbered}

{{< include _includes/dataB.qmd >}}

## Public Opinion: News and E-mails {.unnumbered}

{{< include _includes/emails4B.qmd >}}


:::
