---
title: "Workshop 4 Group G"
---

```{r setupG4, include=FALSE}

#define variables for each group: city and hospital name, infectious agent and disease, group letter
city_name <- "Glenleith"
hosp_name <- "Riverview"
dis_name <- "XDR tuberculosis"
inf_agent <- "Mycobacterium tuberculosis"
inf_type <- "bact"
group <- "G"
groupseed <- 1116
```
{{< include ../workshop3/_includes/setup.qmd >}}
{{< include _includes/setup4.qmd >}}

::: panel-tabset
## Minutes from the last Emergency Pandemic Response Team Meeting {.unnumbered}

At the previous emergency pandemic response team meeting, the following action points were agreed:

* Start analysing the patient strains sequence data for presence of resistance genes and begin drug susceptibility testing using rapid molecular testing or culture methods, and start patients with confirmed TB on the 6 months all oral regimen BPaLM/BPaL

* Create posters, TV ads, public health announcements etc with information about transmission, symptoms

* Encourage public to be vaccinated, especially children and close contacts of confirmed cases

* Contact local authorities about potentially outsourcing spare staff equipment, ventilators, PPE, overflow sites

* Track and trace on the patients

## Data collected for the current Emergency Pandemic Response Team Meeting {.unnumbered}

{{< include _includes/dataG.qmd >}}

## Public Opinion: News and E-mails {.unnumbered}

{{< include _includes/emails4G.qmd >}}


:::
