---
title: "Workshop 4 Group I1"
---

```{r setupI14, include=FALSE}

#define variables for each group: city and hospital name, infectious agent and disease, group letter
city_name <- "Ardkeld"
hosp_name <- "Riverview"
dis_name <- "anthrax"
inf_agent <- "Bacillus anthracis"
inf_type <- "bact"
group <- "I"
groupseed <- 3279
```
{{< include ../workshop3/_includes/setup.qmd >}}
{{< include _includes/setup4.qmd >}}

::: panel-tabset
## Minutes from the last Emergency Pandemic Response Team Meeting {.unnumbered}

At the previous emergency pandemic response team meeting, the following action points were agreed:


* Interview the patients currently known to be infected with anthrax. Identify what variation of the infection they have (cutaneous, respiratory, etc.) 

* Post identification of source (food source, building, etc.) cut it off. In the case of a building, it should be shut immediately (condemned) and decontaminated. 

* Vaccination program. Encourage people to get vaccinated to minimise infection. 

* Hospital policy for disposal of bodies. No autopsy. 

* Investigate local farms and livestock. Testing the soil and the animals for the presence of the spores.
Vaccinate the animals and farm staff. (2)
Biochemical assays testing for catalase(+), oxidase(-). Gram positive rods. That are neg for haemolysis. (4)


## Data collected for the current Emergency Pandemic Response Team Meeting {.unnumbered}

{{< include _includes/dataI1.qmd >}}

## Public Opinion: News and E-mails {.unnumbered}

{{< include _includes/emails4I1.qmd >}}


:::
