---
title: "Group F - References"
---

```{r refF, include=FALSE}

#define variables for each group: city and hospital name, infectious agent and disease, group letter
city_name <- "Glenmarigg"
hosp_name <- "Royal Jubilee"
dis_name <- "meningitis"
inf_agent <- "Neisseria meningitidis"
inf_type <- "bact"
group <- "F"
set.seed(678) # Ensures reproducibility
```

::: callout-tip
The following list of references is provided as a starting place for you to begin exploring various aspects of *`r inf_agent`* biology, diagnostics, epidemiology, and treatment. However, this is by no means an exhaustive list: you should further explore the relevant peer-reviewed literature independently.  
:::

::: panel-tabset

## Selected *`r inf_agent`* Public Health Literature {.unnumbered}

* [Guidance for public health management of meningococcal disease in the UK](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/829326/PHE_meningo_disease_guideline.pdf)

* [Meningococcal ACWY vaccine surveillance and data - Public Health Scotland](https://publichealthscotland.scot/our-areas-of-work/immunisations/immunisations-by-vaccine/meningococcal-acwy-vaccine-men-acwy/surveillance-and-data/)

* [National enhanced surveillance of vaccination programmes targeting invasive meningococcal disease in England (UKHSA)](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1124997/UKHSA-meningococcal-surveillance-december-2022.pdf)

* [Meningococcal Disease Risk Factors](https://www.cdc.gov/meningococcal/about/risk-factors.html)

* [Meningitis and septicaemia: prevention and management in higher education institutions](https://www.gov.uk/government/publications/meningitis-and-septicaemia-prevention-and-management-in-higher-education-institutions)

* [WHO Initiative: Defeating Meningitis by 2030](https://www.who.int/initiatives/defeating-meningitis-by-2030)

* [Meningitis Now Resources](https://www.meningitisnow.org/how-we-help/resources/)

* [Meningitis Research Foundation: Help and Support Resources](https://www.meningitis.org/get-support/help-and-support-resources)

* Webb, Adam et al. “Cross-Sectional Study of University Students' Attitudes to 'On Campus' Delivery of COVID-19, MenACWY and MMR Vaccines and Future-Proofing Vaccine Roll-Out Strategies.” Vaccines vol. 10,8 1287. 10 Aug. 2022, doi:10.3390/vaccines10081287

* Sulis, Giorgia et al. “A comparison of national vaccination policies to prevent serogroup B meningococcal disease.” Vaccine vol. 40,26 (2022): 3647-3654.

* Taha, Muhamed-Kheir et al. “Equity in vaccination policies to overcome social deprivation as a risk factor for invasive meningococcal disease.” Expert review of vaccines vol. 21,5 (2022): 659-674. doi:10.1080/14760584.2022.2052048

* Martinón-Torres, Federico et al. “Evolving strategies for meningococcal vaccination in Europe: Overview and key determinants for current and future considerations.” Pathogens and global health vol. 116,2 (2022): 85-98. doi:10.1080/20477724.2021.1972663

* Alderson, Mark R et al. “Surveillance and control of meningococcal disease in the COVID-19 era: A Global Meningococcal Initiative review.” The Journal of infection vol. 84,3 (2022): 289-296. doi:10.1016/j.jinf.2021.11.016

* Muttalif, Abdul Razak et al. “Incidence and Prevention of Invasive Meningococcal Disease in Global Mass Gathering Events.” Infectious diseases and therapy vol. 8,4 (2019): 569-579. doi:10.1007/s40121-019-00262-9

## Selected *`r inf_agent`* Diagnostics and Treatment Literature {.unnumbered}

* [Identification and Characterization of <i>Neisseria meningitidis</i> (CDC)](https://www.cdc.gov/meningitis/lab-manual/chpt07-id-characterization-nm.html)

* [BMJ Best Practice - Bacterial Meningitis in Adults](https://bestpractice.bmj.com/topics/en-gb/3000104)

* [Meningitis (bacterial) and meningococcal septicaemia in under 16s: recognition, diagnosis and management (NICE)](https://www.nice.org.uk/guidance/cg102)

* [Identification and Characterization of <i>Neisseria meningitidis</i> (CDC)](https://www.cdc.gov/meningitis/lab-manual/chpt07-id-characterization-nm.html)

* [Meningococcal Disease: Clinical Info (CDC)](https://www.cdc.gov/meningococcal/clinical-info.html)

* [BMJ Best Practice - Bacterial Meningitis in Adults](https://bestpractice.bmj.com/topics/en-gb/3000104)

* [Meningitis (bacterial) and meningococcal septicaemia in under 16s: recognition, diagnosis and management (NICE)](https://www.nice.org.uk/guidance/cg102)

* [Meningococcal Disease: Infection Control in Healthcare Personnel: Epidemiology and Control of Selected Infections Transmitted Among Healthcare Personnel and Patients](https://www.cdc.gov/infectioncontrol/guidelines/healthcare-personnel/selected-infections/meningococcal-disease.html)

* Hasbun, Rodrigo. “Progress and Challenges in Bacterial Meningitis: A Review.” JAMA vol. 328,21 (2022): 2147-2154. doi:10.1001/jama.2022.20521

* McNamara, Lucy A et al. “Mass chemoprophylaxis for control of outbreaks of meningococcal disease.” The Lancet. Infectious diseases vol. 18,9 (2018): e272-e281.

* Davis, L C et al. “Meningococcal disease in a backpackers hostel in Scotland: a risk assessment for prophylaxis.” Euro surveillance : bulletin Europeen sur les maladies transmissibles = European communicable disease bulletin vol. 14,31 19291. 6 Aug. 2009, doi:10.2807/ese.14.31.19291-en

* Morsli, Madjid et al. “Real-time metagenomics-based diagnosis of community-acquired meningitis: A prospective series, southern France.” EBioMedicine vol. 84 (2022): 104247.

* Sharma, Nupur et al. “Clinical use of multiplex-PCR for the diagnosis of acute bacterial meningitis.” Journal of family medicine and primary care vol. 11,2 (2022): 593-598.

## Selected *`r inf_agent`* Epidemiology Literature {.unnumbered}

* [<i>Neisseria</i> spp. pubMLST](https://pubmlst.org/organisms/neisseria-spp)

* Schoen, Christoph et al. “Whole-genome comparison of disease and carriage strains provides insights into virulence evolution in <i>Neisseria meningitidis</i>.” Proceedings of the National Academy of Sciences of the United States of America vol. 105,9 (2008): 3473-8. doi:10.1073/pnas.0800151105

* Itsko, Mark et al. “Enhancing Meningococcal Genomic Surveillance in the Meningitis Belt Using High-Resolution Culture-Free Whole-Genome Sequencing.” The Journal of infectious diseases vol. 226,4 (2022): 729-737. doi:10.1093/infdis/jiac104

* de Souza Santos, Debora Ribeiro et al. “High-Resolution Melting (HRM) for rapid MLST analysis of <i>Neisseria meningitidis</i>.” Journal of microbiological methods vol. 200 (2022): 106557. doi:10.1016/j.mimet.2022.106557

* Taha S, Hong E, Denizon M, et al. The rapid rebound of invasive meningococcal disease in France at the end of 2022. J Infect Public Health. 2023;16(12):1954-1960. doi:10.1016/j.jiph.2023.10.001

* Clark SA, Campbell H, Ribeiro S, et al. Epidemiological and strain characteristics of invasive meningococcal disease prior to, during and after COVID-19 pandemic restrictions in England. J Infect. 2023;87(5):385-391. doi:10.1016/j.jinf.2023.09.002

* Eriksson L, Johannesen TB, Stenmark B, et al. Genetic variants linked to the phenotypic outcome of invasive disease and carriage of <i>Neisseria meningitidis</i>. Microb Genom. 2023;9(10):001124. doi:10.1099/mgen.0.001124

* Yang Z, Guarracino A, Biggs PJ, et al. Pangenome graphs in infectious disease: a comprehensive genetic variation analysis of <i>Neisseria meningitidis</i> leveraging Oxford Nanopore long reads. Front Genet. 2023;14:1225248. Published 2023 Aug 10. doi:10.3389/fgene.2023.1225248

* Miellet WR, Pluister G, Sikking M, et al. Surveillance of <i>Neisseria meningitidis</i> carriage four years after menACWY vaccine implementation in the Netherlands reveals decline in vaccine-type and rise in genogroup e circulation. Vaccine. 2023;41(34):4927-4932. doi:10.1016/j.vaccine.2023.06.078

* Madariaga-Troncoso D, Leyton-Carcaman B, Garcia M, Kawai M, Abanto Marin M. Comprehensive Genome Analysis of <i>Neisseria meningitidis</i> from South America Reveals a Distinctive Pathogenicity-Related Prophage Repertoire. Int J Mol Sci. 2022;23(24):15731. Published 2022 Dec 12. doi:10.3390/ijms232415731

* Itsko M, Topaz N, Ousmane-Traoré S, et al. Enhancing Meningococcal Genomic Surveillance in the Meningitis Belt Using High-Resolution Culture-Free Whole-Genome Sequencing. J Infect Dis. 2022;226(4):729-737. doi:10.1093/infdis/jiac104

* Earle SG, Lobanovska M, Lavender H, et al. Genome-wide association studies reveal the role of polymorphisms affecting factor H binding protein expression in host invasion by <i>Neisseria meningitidis</i>. PLoS Pathog. 2021;17(10):e1009992. Published 2021 Oct 18. doi:10.1371/journal.ppat.1009992

* MacLennan JM, Rodrigues CMC, Bratcher HB, et al. Meningococcal carriage in periods of high and low invasive meningococcal disease incidence in the UK: comparison of UKMenCar1-4 cross-sectional survey results [published correction appears in Lancet Infect Dis. 2021 May;21(5):e122] [published correction appears in Lancet Infect Dis. 2021 Jul;21(7):e182]. Lancet Infect Dis. 2021;21(5):677-687. doi:10.1016/S1473-3099(20)30842-2

::: 

