---
title: "Group F"
---

```{r setupF, include=FALSE}

#define variables for each group: city and hospital name, infectious agent and disease, group letter
city_name <- "Glenmarigg"
hosp_name <- "Royal Jubilee"
dis_name <- "meningitis"
inf_agent <- "Neisseria meningitidis"
inf_type <- "bact"
group <- "F"
set.seed(678) # Ensures reproducibility
paper_name <- sample(c("Times", "Courier", "Express", "Chronicle", "Gazette", "Herald", "News", "Metro", "Sentinel", "Beacon", "Journal"), 1)

#Define variables for the dates: 
workshop3_date <- as.Date("2025-02-28", format="%Y-%m-%d")
news_date <- workshop3_date - sample(c(3:6), 1)
news_date <- format(news_date, "%d %B, %Y")


```

::: panel-tabset
## Pandemic Outbreak {.unnumbered}

{{< include _includes/news1.qmd >}}

## `r city_name` City Info {.unnumbered}

{{< include _includes/city.qmd >}}

## *`r inf_agent`* {.unnumbered}

{{< include _includes/pathogenF.qmd >}}

## *`r inf_agent`* - suggested reading {.unnumbered}

{{< include _includes/refF.qmd >}}

## Public Opinion: News and E-mails {.unnumbered}

{{< include _includes/emails3.qmd >}}

## Data Collected for the Pandemic Response Committee Meeting {.unnumbered}

{{< include _includes/data.qmd >}}

* You can find more key information about the main hospital in `r city_name`, the `r hosp_name` in the [hospital dashboard](dashboardA.qmd).

### Epidemiological Data {.unnumbered}

A team of scientists working together have in a PHS lab have isolated and cultured <i>Neisseria meningitidis</i> (following standard procedures) from a number of patient samples taken during this outbreak; isolated DNA from these cultures; sequenced this DNA using an Illumina MiSeq platform; assembled the short paired-end reads; and compared these assemblies to the extant <i>Neisseria</i> sequences available in the NCBI databases. The results of these experiments are summarised in the table below. 

<table>
<table border="1">
  <tr>
    <th>Patient  </th>
    <th>NCBI accession of closest database match</th>
  </tr>
  <tr>
    <td>1</td>
    <td>GCA_003496325.1</td>
  </tr>
  <tr>
    <td>2</td>
    <td>GCA_003977735.1</td>
  </tr>
  <tr>
    <td>3</td>
    <td>GCA_003496325.1</td>
  </tr>
  <tr>
    <td>4</td>
    <td>GCA_003496325.1</td>
  </tr>
  <tr>
    <td>5</td>
    <td>GCA_003496325.1</td>
  </tr>
  <tr>
    <td>6</td>
    <td>GCA_003496325.1</td>
  </tr>
    <tr>
    <td>7</td>
    <td>GCA_003496325.1</td>
  </tr>
  <tr>
    <td>8</td>
    <td>GCA_003496325.1</td>
  </tr>
  <tr>
    <td>9</td>
    <td>GCA_003977745.1</td>
  </tr>
    <tr>
    <td>10</td>
    <td>GCA_003496325.1</td>
  </tr>
</table>  
<br><br>

## City and Hospital Pandemic Planning Resources {.unnumbered}

{{< include _includes/briefing.qmd >}}

## Other useful resources/links {.unnumbered}

{{< include _includes/resources.qmd >}}

:::
